const QUOTES: [quote: string, author: string][] = [
	['Představte si to ticho, kdyby lidé říkali jen to, co vědí.', 'Karel Čapek'],
	['Člověk je sám i mezi lidmi.', 'Antoine de Saint-Exupéry'],
	['Peklo je prázdné, ďáblové jsou mezi námi.', 'William Shakespeare'],
	['Ne všichni, kdo bloudí, jsou ztraceni.', 'J. R. R. Tolkien'],
	['Kdo z hrdosti nepřizná vlastní chyby, nemá hrdost.', 'Charles Dickens'],
	['Neporozumí dnešku, kdo nezná včerejšek.', 'Alois Jírásek'],
	['Lepší je zemřít na nohou než žít na kolenou.', 'Jean Paul Sartre'],
	['Čtenář prožije tisíc životů, než zemře. Človek, jenž nikdy nečte, prožije jen jeden.', 'George R. R. Martin'],
	[
		'Pouze dvě věci jsou nekonečné. Vesmír a lidská hloupost. U té první si tím však nejsem tak jist.',
		'Albert Einstein'
	],
	['Dobré knihy neprozradí všechna svá tajemství najednou.', 'Stephen King'],
	['Nikdy neodkládám na zítřek, co lze udělat pozítří.', 'Oscar Wilde'],
	['Kde blb, tam nebezpečno.', 'Jan Werich'],
	['Vyslyš každého, ale ponech si svůj úsudek.', 'William Shakespeare'],
	['Kdo chce, hledá způsob. Kdo nechce, hledá důvod.', 'Jan Werich'],
	['Historie ke mně bude laskavá, protože ji mám v úmyslu psát.', 'Winston Churchill'],
	['Když procházíš peklem, nezastavuj se.', 'Winston Churchill'],
	['Strach je reakce. Odvaha je rozhodnutí.', 'Winston Churchill'],
	['Pravda a láska musí zvítězit nad lží a nenávistí!', 'Václav Havel'],
	['Nejlepší smrt je neočekávaná.', 'Gaius Julius Caesar'],
	['Lidé rádi věří tomu, co si přejí.', 'Gaius Julius Caesar'],
	['Přišel jsem, viděl jsem, zvítězil jsem.', 'Gaius Julius Caesar'],
	['Kostky jsou vrženy.', 'Gaius Julius Caesar'],
	['Kdybych měl 8 hodin na pokácení stromu, 6 bych strávil broušení sekyry.', 'Abraham Lincoln'],
	['Taktnost je schopnost popisovat lidi tak, jak se oni sami vidí.', 'Abraham Lincoln'],
	['Mým nejlepším přítelem je člověk, který mi dá knihu, kterou jsem nečetl.', 'Abraham Lincoln'],
	['Chceš-li poznat charakter člověka, dej mu moc.', ''],
	['Tak jako nebudu otrokem, nebudu ani otrokářem. To je moje představa demokracie.', 'Abraham Lincoln'],
	['Kdo ovládá minulost, ovládá budoucnost. Kdo ovládá přítomnost, ovládá minulost.', 'George Orwell'],
	['Jestliže svoboda slova vůbec něco znamená, potom je to právo říkat lidem to, co nechtějí slyšet.', 'George Orwell'],
	['Česko je nejkrásnější zemí na světě. Jen je škoda, že zde žijí Češi.', 'Vlasta Burian'],
	['Ještě se nestalo, aby to nějak nedopadlo.', 'Vlasta Burian'],
	['Nejsnadněji zakopne stonožka.', 'Vlasta Burian'],
	['Pokud skutečně milujete přírodu, najdete krásu ve všem.', 'Vincent Van Gogh'],
	['Jsou lidé, kteří vlastní a lidé, kteří žijí.', 'Miloš Zeman'],
	['Největší umění života je umění vědět, kdy skončit.', 'Miloš Zeman'],
	['Chcete-li vybudovat velký podnik, vybudujte nejdříve sebe.', 'Tomáš Baťa'],
	['Snažte se dělat věci nejlépe na světě a svět si vyšlape cestičku k Vašim dveřím.', 'Tomáš Baťa'],
	['Každý člověk je zámožný, pokud má zdravé ruce a trochu rozumu.', 'Tomáš Baťa'],
	['Boj je podstatou života. Kdo nebojuje, nemůže ani zvítězit.', 'Tomáš Baťa'],
	['Když všichni mluví o nemožnostech, hledej možnosti.', 'Tomáš Baťa'],
	['Neříkej, že to nejde, raději řekni, že to zatím neumíš.', 'Tomáš Baťa'],
	['Dělejme třeba nejnepatrnější věc na světě, ale dělejme ji nejlépe.', 'Tomáš Baťa'],
	['Najít správný směr, mezi opatrností a odvahou je to největší umění.', 'Tomáš Baťa'],
	['Než něco řeknu, musím přemýšlet, co mi ten druhý na to odpoví.', 'Tomáš Baťa'],
	['Co chceš, můžeš.', 'Tomáš Baťa'],
	['Kniha musí být sekerou pro zamrzlé moře ukryté v nás.', 'Franz Kafka'],
	['Knihy jsou droga.', 'Franz Kafka'],
	['Není větší škody nad ztracený čas.', 'Michelangelo Buonarroti'],
	['Víra v sebe sama je nejlepší a nejbezpečnější cesta.', 'Michelangelo Buonarroti'],
	[
		'Kdyby lidé věděli, jak tvrdě jsem pracoval na svých dílech, nepovažovali by mě za génia.',
		'Michelangelo Buonarroti'
	],
	['Maličkosti dělají dokonalost, ale dokonalost není maličkost.', 'Michelangelo Buonarroti'],
	['Vlídnost bere i jed hadům.', 'Michelangelo Buonarroti'],
	['Tam, kde nám chybějí slova, pomohou skutky.', 'Michelangelo Buonarroti'],
	['Je mi jedno, že mi ukradli můj nápad… Vadí mi ale, že nemají žádné vlastní nápady.', 'Nikola Tesla'],
	['Být sám, to je tajemství vynálezu; v samotě se rodí myšlenky.', 'Nikola Tesla'],
	['Všechny naše sny se mohou stát skutečností, pokud máme odvahu je následovat.', 'Walt Disney'],
	['Když o tom dokážeš snít, dokážeš to udělat.', 'Walt Disney'],
	['Nejlepší způsob, jak se do něčeho pustit, je přestat o tom mluvit a začít to dělat.', 'Walt Disney'],
	['Kdo je pánem Čech je pánem Evropy.', 'Otto Von Bismarck'],
	['Nejlepší obrana je útok.', 'Otto Von Bismarck'],
	['Všechno se zdá nemožné, dokud to neuděláš.', 'Nelson Mandela'],
	['Nikdy jsem nepotkal nikoho tak hloupého, abych se od něj něčemu nepřiučil.', 'Galileo Galilei'],
	['Tvrdá práce je bezcenná pro ty, kteří nevěří v sebe.', 'Naruto Uzumaki'],
	['Mít strach není žádná hanba, říkával mi můj otec, podstatné je, jak se k němu postavíš.', 'Jon Snow Targaryen'],
	['Ty nejlepší lži v sobě vždycky mají kousek pravdy.', 'Cersei Lannister'],
	['Opici banán z ruky nevymluvíš.', 'Tomáš Hájek']
];

export const get_quote = () => QUOTES[Math.floor(Math.random() * QUOTES.length)];
